### ISSUE TITLE
[PE-D][Tester A] Right side of content being cut off (Resize)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-3/tp#195]
![Screenshot 2023-11-03 at 3.47.44 PM.png](https://raw.githubusercontent.com/LimJH2002/ped/main/files/8ba9a14b-4929-4009-a374-6d84ce4b9722.png)

Though not very serious, but if resize to the minimum allowed width, the right side of the content is being cut off, leading to suboptimum viewing experience.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: LimJH2002/ped#2

**Comment by Chandan8186** [comment]
Not allowed to fix as per [FAQ Q8](https://nus-cs2103-ay2324s1.github.io/website/schedule/week12/project.html#2-start-fixing-ped-bugs-before-the-tutorial)

**Comment by timleow** [comment]
Since we are not allowed to fix Ui changes, I will be closing this issue.

Again, in our defence TaskHub is opened at a reasonable size by default, where a reasonable number of Employees, Tasks and Projects can be viewed.


<img width="856" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-3/tp/assets/64006665/885d5246-b1e3-4e38-811b-e01ca13df518">
